# Generated by Django 4.0.4 on 2022-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.FloatField(blank=True, max_length=1000, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=1000, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
