# Generated by Django 4.0.4 on 2022-06-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_expenses_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
