# Generated by Django 4.0.4 on 2022-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.IntegerField(blank=True, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
